Suppress broken semicolon_if_nothing_returned lint
Gonna assume this is due to https://github.com/rust-lang/rust-clippy/issues/7768.

    error: consider adding a `;` to the last statement for consistent formatting
      --> src/lib.rs:84:9
       |
    84 | /         dtoa! {
    85 | |             floating_type: f32,
    86 | |             significand_type: u32,
    87 | |             exponent_type: i32,
    ...  |
    98 | |             min_power: (-36),
    99 | |         };
       | |__________^
       |
       = note: `-D clippy::semicolon-if-nothing-returned` implied by `-D clippy::pedantic`
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#semicolon_if_nothing_returned
    help: add a `;` here
       |
    84 ~         dtoa! {
    85 +             floating_type: f32,
    86 +             significand_type: u32,
    87 +             exponent_type: i32,
    88 +
    89 +             diy_significand_size: 32,
     ...

    error: consider adding a `;` to the last statement for consistent formatting
       --> src/lib.rs:106:9
        |
    106 | /         dtoa! {
    107 | |             floating_type: f64,
    108 | |             significand_type: u64,
    109 | |             exponent_type: isize,
    ...   |
    120 | |             min_power: (-348),
    121 | |         };
        | |__________^
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#semicolon_if_nothing_returned
    help: add a `;` here
        |
    106 ~         dtoa! {
    107 +             floating_type: f64,
    108 +             significand_type: u64,
    109 +             exponent_type: isize,
    110 +
    111 +             diy_significand_size: 64,
      ...